export const PUBLIC_CODES = [
  "AUTH_REQUIRED", "ORIGIN_REJECTED", "INVALID_REQUEST", "REQUEST_TOO_LARGE",
  "DRIVE_NOT_CONNECTED", "DRIVE_REAUTH_REQUIRED", "DRIVE_ACCOUNT_MISMATCH",
  "DRIVE_REMOTE_MISMATCH",
  "DRIVE_FILE_DELETE_CONFLICT",
  "IDEMPOTENCY_CONFLICT", "OAUTH_STATE_INVALID", "OAUTH_STATE_EXPIRED",
  "OAUTH_STATE_REPLAYED", "OAUTH_SCOPE_REJECTED", "OAUTH_REFRESH_TOKEN_MISSING",
  "DRIVE_QUOTA_STALE", "DRIVE_STORAGE_HIGH", "NEON_STORAGE_HIGH", "QUOTA_INVALID",
  "UPLOAD_TYPE_REJECTED", "UPLOAD_TOO_LARGE", "UPLOAD_SESSION_EXPIRED",
  "UPLOAD_REMOTE_MISMATCH", "UPLOAD_RETRY_EXHAUSTED", "DRIVE_RATE_LIMITED",
  "DRIVE_TEMPORARILY_UNAVAILABLE", "DRIVE_PROVIDER_REJECTED",
  "WORKER_ENROLLMENT_INVALID", "WORKER_AUTH_REQUIRED", "WORKER_SESSION_EXPIRED",
  "WORKER_REVOKED", "WORKER_DOCTOR_FAILED", "WORKER_INCOMPATIBLE",
  "LEASE_LOST", "NO_JOB_AVAILABLE", "JOB_NOT_QUEUEABLE",
  "TTS_PREVIEW_UNAVAILABLE",
] as const;

export type PublicCode = (typeof PUBLIC_CODES)[number];

export class AppError extends Error {
  constructor(readonly code: PublicCode, readonly status: number) {
    super(code);
  }
}

export function publicErrorBody(error: AppError): Readonly<{ code: PublicCode }> {
  return { code: error.code };
}

export const DRIVE_AUDIT_EVENTS = [
  "DRIVE_CONNECT_STARTED", "DRIVE_CONNECTED", "DRIVE_REAUTH_REQUIRED",
  "DRIVE_DISCONNECTED", "PROJECT_CREATED", "UPLOAD_SESSION_CREATED",
  "UPLOAD_COMPLETED", "UPLOAD_CANCELLED", "UPLOAD_FAILED",
  "FREE_TIER_MODE_CHANGED",
] as const;
