[unix_http_server]
file=/run/ytb-vps-supervisor.sock
chmod=0700

[supervisord]
logfile=/srv/ytb-vps/logs/supervisord.log
logfile_maxbytes=20MB
logfile_backups=3
pidfile=/run/ytb-vps-supervisord.pid
childlogdir=/srv/ytb-vps/logs
nodaemon=false
silent=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/ytb-vps-supervisor.sock

[include]
files=/etc/supervisor/conf.d/ytb-vps.conf
